# -*- coding: utf-8 -*-
"""manual_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mryiqgETf-WMhVMB-PDuvHXyyqGFvsoK
"""

!pip install twilio

import cv2
import numpy as np
import smtplib
from tensorflow.keras.preprocessing import image 
from keras.models  import load_model
from twilio.rest import Client

model = load_model(r'/content/drive/MyDrive/model file/forest1 (2).h5') 

    
#give any random image path
img = image.load_img(r"/content/drive/MyDrive/forest fire/Dataset/train_set/with fire/with fire (1).png",target_size= (64,64))#loading of the image
x = image.img_to_array(img)
#expand the image shape
x = np.expand_dims(x,axis = 0)
preds=model.predict(x)
pred=np.argmax(preds,axis=1)
    

if pred[0]==1:
       account_sid = 'AC8b5221b34406db8b4cc42c18afb15901'
       auth_token = '17f628fc77996909ec040b321b771173'
       client = Client(account_sid, auth_token)

       message = client.messages.create(
       messaging_service_sid='MGaf95938e5e0ffcf0cae9f7732329b67d',
       body='fire detected please take an immediate action',
       to='+919347657960'  ) 
       print(message.sid)
    
       print('Fire Detected')
       print ('SMS sent!')
    
else:
    print("no danger")

